// <auto-generated />
namespace cima.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRequiredDataAnnotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRequiredDataAnnotation));
        
        string IMigrationMetadata.Id
        {
            get { return "202106250832159_AddRequiredDataAnnotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
